on: push
name: Tests
jobs:
  go:
    strategy:
      matrix:
        go: ["^1.17.0", "^1.18.0", "^1.19.0"]
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: ./tests/constants.sh
